# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


variables:
  dockerId: RGDEVContainers

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: mvnsettings
  displayName: 'Download Maven settings'
  inputs:
    secureFile: 'settings.xml'
- script: mvn clean package -P container -DskipTests
  displayName: 'Packaging jar '
- script:  docker login -u $(dockerId) -p $(pswdreg) rgdevcontainers.azurecr.io 
  displayName: 'Login to Docker Azure Container Registry'
- script:  mvn dockerfile:build dockerfile:push
  displayName: 'Build and Push docker image'
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
